disabled_rules:
  - trailing_whitespace
  - identifier_name
opt_in_rules:
  - empty_count
  - force_unwrapping
  - closure_spacing
excluded:
  - Pods
  - R.generated.swift
  - build
# Configure rules
force_cast: warning
force_try:
  severity: warning
line_length: 150 
type_body_length:
  - 300
  - 500
file_length:
  warning: 1000
  error: 1500
